server:
  port: 8080 # ????????????? ???? ??? API Gateway ? ??? ????? ??????? ????? ? ???? ???????

spring:
  application:
    name: api-gateway # ??? ???????, ??? ??????? ?? ???????????????? ? Eureka

  cloud:
    gateway:
      routes: # ?????????? ???????? (???????), ?? ??????? ????? ???????????? API Gateway
        - id: user-service # ?????????? ????????????? ???????? (????????????, ?? ?????????? ???????????)
          uri: lb://user-service # lb:// ???????? LoadBalancer (?????????? Eureka), ??? ?????? ????????? ? spring.application.name ? ???????? ???????
          predicates:
            - Path=/api/users/** # ??? ???????? ??????? ?? ???? /api/users/** ????? ?????????????? ? user-service

eureka:
  client:
    register-with-eureka: true # ???????????? API Gateway ? Eureka, ????? ??? ????? ?????? ?????? ???????
    fetch-registry: true       # ????????? API Gateway ???????? ?????? ?????? ?????????????????? ???????? ?? Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka # ????????? URL Eureka-???????

  instance:
    prefer-ip-address: true # ??????? Eureka ???????????? IP-????? ?????? hostname (???? ????? ????????, ???????? ? Docker)

